- name: "bug 🐛"
  color: "d73a4a"
  description: "Something isn't working as expected"

- name: "enhancement ✨"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation 📚"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "good first issue 🎯"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted 🤝"
  color: "008672"
  description: "Extra attention is needed"

- name: "performance 🚀"
  color: "f3f99d"
  description: "Performance related improvements"

- name: "breaking change ⚠️"
  color: "d93f0b"
  description: "Changes that break backward compatibility"

- name: "dependencies 📦"
  color: "0366d6"
  description: "Updates or modifications to dependencies" 